### ISSUE TITLE
Add ADR

### ISSUE THREAD

**Issue by koppor** [CryptoCatalog/CryptoCatalog#6]
There should be an [architectural decision record](https://adr.github.io/) be recorded, why a java-based implementation is chosen. I propose to use [MADR](https://adr.github.io/madr/) for that.

With the [ultimate comparison framework](https://ultimate-comparisons.github.io/) we offer a general solution to compare libraries and provide details.

See https://ultimate-comparisons.github.io/ultimate-webIDE-comparison/ for en example, which compares Web-based IDEs.

**Comment by schneisn** [comment]
Thanks for the input. We are going to include the architectural decision record.  
The ultimate comparison framework looks like a good solution to compare cryptographic libraries, but we decided to continue with our design. Any additional suggestions to improve our project are always welcome 😃
